name: Release Plugin

on:
  push:
    tags:
      - 'v*'        # сработает на теги вида v1.0.0, v2.3.1 и т.п.

permissions:
  contents: write   # нужно, чтобы создать Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build ZIP
        run: |
          cd tracker-manager
          zip -r ../tracker-manager-${{ steps.version.outputs.VERSION }}.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.VERSION }}
          tag_name: ${{ steps.version.outputs.VERSION }}
          files: tracker-manager-${{ steps.version.outputs.VERSION }}.zip
          generate_release_notes: true
